spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.160.9:9092,192.168.160.9:9093,192.168.160.9:9094
          autoCreateTopics: true
      dynamicDestinations: MELIIRTHXXX,AYBKIRTHXXX
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:2020/eureka
